SELECT CP1.CART_ID FROM CART_PRODUCTS AS CP1
INNER JOIN CART_PRODUCTS AS CP2 ON CP1.CART_ID = CP2.CART_ID
WHERE CP1.NAME IN("Milk") AND CP2.NAME IN("Yogurt")
GROUP BY CP1.CART_ID
ORDER BY CP1.CART_ID;